CAMPUS-T-751 fix entity code length
campus-mobile/campus-parser-kotlin-sdk pull request #17
Opened 2023-08-22 07:04 UTC by LeonidZezulya

2023-08-22 07:05 UTC, LeonidZezulya commented
оказалось, что существуют коды длиной 1 у некоторых вузов, а валидация не даёт такие сущности на сервер заливать, хотя они валидные фактически
https://www.altstu.ru/main/schedule/teacher/5/
вот пример

2023-08-22 11:02 UTC, Alex009 requested changes

2023-08-22 11:02 UTC, Alex009 commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/model/Entity.kt
>          assertLength(::newCode, length = 1)
почему тогда newCode не изменился?

2023-08-23 03:56 UTC, LeonidZezulya commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/model/Entity.kt
>          assertLength(::newCode, length = 1)
ну, по идее, тоже надо, просто мы им не пользуемся почти нигде

2023-08-23 05:39 UTC, Alex009 approved these changes

2023-08-23 05:39 UTC, merged