CAMPUS-T-693 update ktor to 2.2.3
campus-mobile/campus-parser-kotlin-sdk pull request #19
Opened 2023-08-31 09:10 UTC by LeonidZezulya

2023-08-31 10:55 UTC, Alex009 requested changes

2023-08-31 10:55 UTC, Alex009 commented on build.gradle.kts
> +        version = "0.6.2"
`0.7.0`. тут не багфикс

2023-08-31 10:55 UTC, Alex009 commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/api/ParserApi.kt
> +    @OptIn(InternalAPI::class)
зачем нам интернал? давай без интернала

2023-08-31 10:55 UTC, Alex009 commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/api/ParserApi.kt
> +    @OptIn(InternalAPI::class)
зачем нам интернал? давай без интернала

2023-08-31 10:55 UTC, Alex009 commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/api/ParserApi.kt
> +        val body = response.body<String>()
тип укажи - https://kmm.icerock.dev/learning/code-style/property-type

2023-08-31 10:55 UTC, Alex009 commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/api/ParserApi.kt
> +        val body = response.body<String>()
тип укажи - https://kmm.icerock.dev/learning/code-style/property-type

2023-08-31 10:55 UTC, Alex009 commented on build.gradle.kts
> +        version = "0.6.2"
и тут нет обратной совместимости. все парсеры надо обновлять до этой версии.

2023-08-31 11:04 UTC, LeonidZezulya commented on build.gradle.kts
> +        version = "0.6.2"
@Alex009 а как оно обратно совместимо может быть? там сильно изменения большие между версиями кторов
парсеры по мере необходимости можно обновлять, там немного должно быть

2023-08-31 11:06 UTC, Alex009 commented on build.gradle.kts
> +        version = "0.6.2"
ты не можешь отдельно один обновить а остальные нет. все парсеры работают в одном приложении. и в это приложение попадет новая версия ктора. а значит те парсеры, где ты не обновишься - просто сломаются. 

обратную совместимость тут не сохранить, потому что парсеры напрямую ктор юзают. таак что просто надо идти и обновлять все

2023-08-31 11:09 UTC, LeonidZezulya commented on build.gradle.kts
> +        version = "0.6.2"
ну вообще я имел в виду те парсеры, которые тут в репозиториях. а которые в campus-jvm - те да, все и сразу надо(

2023-08-31 11:16 UTC, Alex009 commented on build.gradle.kts
> +        version = "0.6.2"
все надо обновлять

2023-08-31 11:21 UTC, Alex009 commented on build.gradle.kts
> +        version = "0.6.2"
https://habr.com/ru/companies/badoo/articles/484712/ почитай, тут более менее просто проблема бинарной совместимости описана

2023-09-01 03:59 UTC, LeonidZezulya commented on build.gradle.kts
> +        version = "0.6.2"
https://campus.jetbrains.space/p/campus/reviews/676/timeline
jvm обновил, счас еще по гитхабовским пробегусь

2023-09-01 03:59 UTC, LeonidZezulya commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/api/ParserApi.kt
> +    @OptIn(InternalAPI::class)
убрал, там setBody просто теперь юзается

2023-09-01 03:59 UTC, LeonidZezulya commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/api/ParserApi.kt
> +    @OptIn(InternalAPI::class)
убрал

2023-09-01 03:59 UTC, LeonidZezulya commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/api/ParserApi.kt
> +        val body = response.body<String>()
готово

2023-09-01 03:59 UTC, LeonidZezulya commented on parser-sdk/src/main/kotlin/ru/campus/parser/sdk/api/ParserApi.kt
> +        val body = response.body<String>()
готово

2023-09-07 09:09 UTC, Alex009 approved these changes

2023-09-07 09:10 UTC, merged